before:
  hooks:
    - go mod tidy
builds:
  - id: texd
    main: ./cmd/texd
    binary: texd
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/digineo/texd.version={{ .Version }}
      - -X github.com/digineo/texd.commit={{ .Commit }}
      - -X github.com/digineo/texd.commitat={{ .CommitDate }}
      - -X github.com/digineo/texd.buildat={{ .Date }}
      - -X github.com/digineo/texd.isdev=0
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      linux: Linux
      darwin: macOS
nfpms:
  - id: texd
    builds: [texd]
    package_name: texd
    vendor: Digineo GmbH
    homepage: https://github.com/digineo/texd
    maintainer: Dominik Menke <dom@digineo.de>
    description: |-
      texd wraps a local TeX installion into a web service.
      Alternatively, texd executes each compilation job in an isolated
      Docker container.
    license: MIT
    formats:
      - deb
    contents:
      - src: debian/texd.service
        dst: /lib/systemd/system/texd.service
    scripts:
      postinstall:  debian/postinstall.sh
      preremove:    debian/preremove.sh
      postremove:   debian/postremove.sh
    overrides:
      deb:
        recommends:
          - latexmk
          - texlive-xetex
  - id: tools
    package_name: texd-tools
    meta: true
    homepage: https://github.com/digineo/texd
    maintainer: Dominik Menke <dom@digineo.de>
    description: |-
      texd-tools includes command line tools useful to interact with
      a texd server. Currenty, the following tools are bundled:

      * texd-render: an HTTP client to compile source files to PDF
    license: MIT
    formats:
      - deb
    contents:
      - src: cmd/texd-render
        dst: /usr/bin/texd-render
    overrides:
      deb:
        dependencies:
          - python3-requests
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
