FROM debian:bullseye-slim

RUN set -ex \
 && apt-get -q update \
 && apt-get -yq upgrade \
 && apt-get -yq install --no-install-recommends \
      lmodern \
      texlive \
      texlive-xetex \
      texlive-binaries \
      texlive-lang-german \
      texlive-science \
      texlive-latex-base \
      texlive-latex-extra \
      texlive-latex-recommended \
      fonts-freefont-ttf \
 && apt-get autoremove --yes \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
