#!/usr/bin/python3

from typing import Union

from base64 import urlsafe_b64encode
from hashlib import sha256
from os import path, pathsep
import sys
import argparse

from urllib.parse import urlparse
import json
import requests


def log(message):
    '''log prints `message` to stderr.'''
    print(message, file=sys.stderr)


def refhash(filename: str) -> str:
    '''refhash calculates the file reference hash for the given file.'''
    h = sha256()
    with open(filename, 'rb') as f:
        for block in iter(lambda: f.read(4096), b''):
            h.update(block)

    digest = urlsafe_b64encode(h.digest()).decode('ascii')
    return f'sha256:{digest}'


def parse_file_arg(arg: str) -> list[str]:
    '''
    parse_file_arg takes a string of the shape 'a:b' and and returns a list
    containing 'a' and 'b'.

    If the string argument has the shape 'a', it returns ['a', 'a'].

    The actual separator is platform-dependent (see `os.pathsep`). On Unix
    systems this is ':', on Windows ';'.
    '''
    parts = arg.split(pathsep, 2)
    if path.isdir(parts[0]):
        raise IsADirectoryError(parts[0])
    if len(parts) == 1:
        parts.append(path.basename(parts[0]))
    return parts

FileList = Union[list[tuple[str, str]], None]
RefList  = Union[list[tuple[str, str, str]], None]

def create_parts(files: FileList = None,
                 refs: RefList = None,
                 missing: list[str] = []):
    '''
    create_parts assembles files and file references into a multipart/form-data
    body suitable for requests.post.

    The file references (`refs`) are only included as whole, if their reference
    hash is not in the missing list.
    '''

    if files == None: files = []
    if refs == None: refs = []

    parts = {}
    num   = 0

    for f in files:
        (form_name, input_file) = f
        log(f'part {num}: {input_file} as {form_name}')
        parts[form_name] = (form_name, open(input_file, 'rb'), 'application/octet-stream')
        num += 1

    for f in refs:
        (form_name, input_file, ref) = f
        if ref in missing:
            log(f'part {num}: {input_file} as {form_name} (storing as {ref}')
            parts[form_name] = (form_name, open(input_file, 'rb'), 'application/x.texd; ref=store')
        else:
            log(f'part {num}: {input_file} as {form_name} (using ref {ref}')
            parts[form_name] = (form_name, ref, 'application/x.texd; ref=use')
        num += 1

    return parts


def missing_refs(r: requests.Response) -> list[str]:
    '''
    missing_refs extracts the missing file references from a request.response.

    (Note: this is not a generic function for arbitrary request.Response
    objects, but tailored to a specific JSON response from texd.)
    '''
    if r.status_code == 422 and r.headers['Content-Type'].startswith('application/json'):
        if (err := r.json()) and err.get('category', None) == 'reference':
            return err['references']
    return []


def render_document(url: str, files: FileList = [], refs: RefList = None) -> requests.Response:
    '''
    render_document sends an HTTP POST request to the given URL.

    The request body includes all files as multipart/form-data entries, plus
    (initially) the reference hashes of all references in `refs`.

    If file references are provided and texd answers with a list of unknown
    references, the request is retried once (this time with all missing
    file references resolved).
    '''
    parts = create_parts(files=files, refs=refs)
    r = requests.post(url, files=parts)

    if (missing := missing_refs(r)) and len(missing) > 0:
        log(f'missing {len(missing)} references, retrying')
        parts = create_parts(files=files, refs=refs, missing=missing)
        r = requests.post(url, files=parts)

    return r


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Simple command line tool to interface with a texd server',
        epilog=f'''
            At least one FILE or REF must be given.
            Both FILE and REF arguments take the format "path" or "path{pathsep}name,
            where "path" is the local path to the file, and "name" is the file name
            to be used on the server, and default to "basename(path)".
        ''')
    parser.add_argument('--files', nargs='+', metavar='FILE', type=str, default=[],
                        help='one or more file to send to the server')
    parser.add_argument('--refs', nargs='+', metavar='REF', type=str, default=[],
                        help=f'one or more file references to use')
    parser.add_argument('--addr', nargs=1, metavar='URI', type=str, default='http://localhost:2201/',
                        help='address of texd server instance (defaults to http://localhost:2201/)')
    parser.add_argument('--error-format', dest="errfmt", nargs=1, type=str, choices=('json', 'full', 'condensed'),
                        help='select error format: "json" (default), "full" or "condesed" TeX log file')
    parser.add_argument('--output', nargs=1, metavar='FILE', type=str, default='-',
                        help='name of output file (defaults to stdout)')
    args = parser.parse_args()

    file_args: FileList = []
    for f in args.files:
        [input_file, form_name] = parse_file_arg(f)
        file_args.append((form_name, input_file))

    ref_args: RefList = []
    for ref in args.refs:
        [input_file, form_name] = parse_file_arg(ref)
        ref_args.append((form_name, input_file, refhash(input_file)))

    if len(file_args) + len(ref_args) == 0:
        parser.print_help()
        exit(2)

    url = urlparse(args.addr)._replace(path="/render")
    if (errfmt := args.errfmt) and errfmt != None:
        url = url._replace(query=f'errors={errfmt[0]}')

    r = render_document(url.geturl(), files=file_args, refs=ref_args)

    if r.status_code == 200:
        if args.output == '-':
            sys.stdout.buffer.write(r.content)
        else:
            outfile = args.output[0]
            with open(outfile, 'wb') as f:
                f.write(r.content)
            log(f'written {outfile}')
        exit(0)

    if r.status_code == 422:
        ct = r.headers['Content-Type']
        if ct.startswith('text/plain'):
            log('texd returned compilation error, these are the logs:')
            log('---')
            log(r.text)
        elif ct.startswith('application/json'):
            log('texd returned error')
            log(json.dumps(r.json(), indent=4))
    else:
        log(f'Unexpected response from texd: {r.status_code}')
        log('---')
        log(r.text)
    exit(1)
